WebApplication1/WebApplication1/Models/Coordinate.cs
namespace WebApplication1.Models
{
    public class Coordinate
    {

        public int Id { get; set; }

        public string Description { get; set; }
        public int XValue { get; set; }
        public int YValue { get; set; }
        public int ZValue { get; set; }
        public string Owner { get; set; }


        public Coordinate()
        {

        }

    }
}

WebApplication1/WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/WebApplication1/Controllers/CoordinatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;
using Microsoft.AspNetCore.Identity;

namespace WebApplication1.Controllers
{

    public class CoordinatesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CoordinatesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Coordinates && current user email
        public async Task<IActionResult> Index()
        {
            return _context.Coordinate != null ?
                        View(await _context.Coordinate.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Coordinate'  is null.");
        }
        // GET: Coordinates/ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        // GET: Coordinates/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(String SearchPhrase)
        {
            return View("Index", await _context.Coordinate.Where(j => j.Description.Contains(SearchPhrase)).ToListAsync());
        }

        // GET: Coordinates/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Coordinate == null)
            {
                return NotFound();
            }

            var coordinate = await _context.Coordinate
                .FirstOrDefaultAsync(m => m.Id == id);
            if (coordinate == null)
            {
                return NotFound();
            }

            return View(coordinate);
        }

        // GET: Coordinates/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Coordinates/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Description,XValue,YValue,ZValue,Owner")] Coordinate coordinate)
        {
            if (ModelState.IsValid)
            {
                _context.Add(coordinate);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(coordinate);
        }

        // GET: Coordinates/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Coordinate == null)
            {
                return NotFound();
            }

            var coordinate = await _context.Coordinate.FindAsync(id);
            if (coordinate == null)
            {
                return NotFound();
            }
            return View(coordinate);
        }

        // POST: Coordinates/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Description,XValue,YValue,ZValue,Owner")] Coordinate coordinate)
        {
            if (id != coordinate.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(coordinate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CoordinateExists(coordinate.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(coordinate);
        }

        // GET: Coordinates/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Coordinate == null)
            {
                return NotFound();
            }

            var coordinate = await _context.Coordinate
                .FirstOrDefaultAsync(m => m.Id == id);
            if (coordinate == null)
            {
                return NotFound();
            }

            return View(coordinate);
        }

        // POST: Coordinates/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Coordinate == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Coordinate'  is null.");
            }
            var coordinate = await _context.Coordinate.FindAsync(id);
            if (coordinate != null)
            {
                _context.Coordinate.Remove(coordinate);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CoordinateExists(int id)
        {
            return (_context.Coordinate?.Any(e => e.Id == id)).GetValueOrDefault();
        }

    }
}

WebApplication1/WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/WebApplication1/Views/Coordinates/Create.cshtml
@model WebApplication1.Models.Coordinate
@using Microsoft.AspNetCore.Identity
@{
    ViewData["Title"] = "Create";
}
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    var usr = await UserManager.GetUserAsync(User);
    var email = usr?.Email;
}
<h1>Create</h1>

<h4>Coordinate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group text-white">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group text-white">
                <label asp-for="XValue" class="control-label"></label>
                <input asp-for="XValue" class="form-control" />
                <span asp-validation-for="XValue" class="text-danger"></span>
            </div>
            <div class="form-group text-white">
                <label asp-for="YValue" class="control-label"></label>
                <input asp-for="YValue" class="form-control" />
                <span asp-validation-for="YValue" class="text-danger"></span>
            </div>
            <div class="form-group text-white">
                <label asp-for="ZValue" class="control-label"></label>
                <input asp-for="ZValue" class="form-control" />
                <span asp-validation-for="ZValue" class="text-danger"></span>
            </div>
            <div class="form-group text-white">
                <label asp-for="Owner" class="control-label"></label>
                <input class = "bg-transparent text-light" value="@email" asp-for="Owner" class="form-control" readonly/>
                <span asp-validation-for="Owner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/WebApplication1/Views/Coordinates/Delete.cshtml
@model WebApplication1.Models.Coordinate

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Coordinate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2 text-light">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10 text-light">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2 text-light">
            @Html.DisplayNameFor(model => model.XValue)
        </dt>
        <dd class = "col-sm-10 text-light">
            @Html.DisplayFor(model => model.XValue)
        </dd>
        <dt class = "col-sm-2 text-light">
            @Html.DisplayNameFor(model => model.YValue)
        </dt>
        <dd class = "col-sm-10 text-light">
            @Html.DisplayFor(model => model.YValue)
        </dd>
        <dt class = "col-sm-2 text-light">
            @Html.DisplayNameFor(model => model.ZValue)
        </dt>
        <dd class = "col-sm-10 text-light">
            @Html.DisplayFor(model => model.ZValue)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication1/WebApplication1/Views/Coordinates/Details.cshtml
@model WebApplication1.Models.Coordinate

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Coordinate</h4>
    <hr />
    <dl class="row text-light">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.XValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.XValue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YValue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ZValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ZValue)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication1/WebApplication1/Views/Coordinates/Edit.cshtml
@model WebApplication1.Models.Coordinate

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Coordinate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Description" class="control-label text-light"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="XValue" class="control-label text-light"></label>
                <input asp-for="XValue" class="form-control" />
                <span asp-validation-for="XValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YValue" class="control-label text-light"></label>
                <input asp-for="YValue" class="form-control" />
                <span asp-validation-for="YValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZValue" class="control-label text-light"></label>
                <input asp-for="ZValue" class="form-control" />
                <span asp-validation-for="ZValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/WebApplication1/Views/Coordinates/Index.cshtml
@model IEnumerable<WebApplication1.Models.Coordinate>
@using Microsoft.AspNetCore.Identity
@{
    ViewData["Title"] = "Index";


}

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    var usr = await UserManager.GetUserAsync(User);
    var email = usr?.Email;
}
<h1>Your Coordinates</h1>

<p>
    <a asp-action="Create">Create Coordinate</a>
</p>
<table class="table bg-transparent text-light">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.XValue)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.YValue)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ZValue)
            </th>
            <th>
                XYZ- (Click to Copy)
            </th>
        </tr>
    </thead>
            
    <tbody>

@foreach (var item in Model) {
            @if (email == item.Owner)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.XValue)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.YValue)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ZValue)
                    </td>
                    <td>
                        <input class="bg-transparent text-light" onclick="this.select(); document.execCommand('copy');" type='text' value='@Html.Raw(item.XValue) @Html.Raw(item.YValue) @Html.Raw(item.ZValue)' readonly/>    
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> 

                    </td>
                </tr>
            }
            
        }
    </tbody>
</table>

WebApplication1/WebApplication1/Views/Coordinates/ShowSearchForm.cshtml
<h4>Search for Coordinates</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">
            <div class="form-group">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApplication1/WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center bg-transparent text-light">
    <h1 class="display-4">Welcome to COORDS</h1>

<div class="slideshow-container">

<div class="SlidesFade fade">
  <img src="@Url.Content("~/Project_Images/Ark-Logo.jpg")"/>
</div> 

<div class="SlidesFade fade">
  <img src="@Url.Content("~/Project_Images/Minecraft.jpg")">
</div>

<div class="SlidesFade fade">
  <img src="@Url.Content("~/Project_Images/Rust-Symbol.jpg")">
</div>

<div class="SlidesFade fade">
  <img src="@Url.Content("~/Project_Images/Valheim_logo.jpg")">
</div>

</div>
<br>

</div>

WebApplication1/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Coordinate Saver</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-body border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">COORDS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Coordinates" asp-action="Index">Your Coordinates</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Coordinates" asp-action="ShowSearchForm">Search</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container">
            &copy; 2022 - COORDS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>